#!/bin/sh

preinst ()
{
    exit 0
}

postinst ()
{
    ln -nsf /var/packages/${SYNOPKG_PKGNAME}/target/bin/backupler /usr/local/bin/backupler
    ln -nsf /var/packages/backupler/target/bin/backupler /usr/local/bin/backupler
    exit 0
}

preuninst ()
{
    exit 0
}

postuninst ()
{
    exit 0
}

preupgrade ()
{
    exit 0
}

postupgrade ()
{
    exit 0
}
